### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [anoff/plantbuddy#15]
Hi @anoff 

I contribute to open source projects by designing logos. I think this project doesn't have a logo. I designed a logo representing the function of the project. If you want to use it, please do a feedback. Have a nice day!

![plantbuddy](https://user-images.githubusercontent.com/36298335/56048929-279f5b80-5d51-11e9-9d98-48c1eca4a027.jpg)

**Comment by anoff** [comment]
Hey @reallinfo ,

looks great. I prefer the first one with the lighter blue. How do you want to license the logo and be mentioned on the repo? Feel free to add respective licenses via PR. I'm fine with anything allows people to use it non-commercially w/o modification i.e. forking w/o violating the license

**Comment by reallinfo** [comment]
Thanks @anoff  I'm using a creative commons license. 

Is it enough to add this link as a comment to pr? 

https://creativecommons.org/licenses/by/4.0/

**Comment by anoff** [comment]
I would prefer to add it explicitly on the readme in an
attributions/license section with you as creator and the license.

**Comment by reallinfo** [comment]
I will send a pr as you wish. you want this? ( I made the color light blue.)

![plantbuddy](https://user-images.githubusercontent.com/36298335/56206931-30947380-6056-11e9-9285-1406881366d6.jpg)

**Comment by anoff** [comment]
👍 looks great

**Comment by reallinfo** [comment]
I sent a pr. I hope it has been as you wish. Are there any problems?

https://github.com/anoff/plantbuddy/pull/16

**Comment by anoff** [comment]
Thanks for your contribution @realinfo!
